### ISSUE TITLE
Request help

### ISSUE THREAD

**Issue by yy0471** [GuHuangAI/DDM-Public#1]
could you give me a wechat?

**Comment by GuHuangAI** [comment]
@tangwy98 please give me your email, and I'll send my vx to you

**Comment by yy0471** [comment]
thank you ! my emial : ***@***.***
















At 2023-12-01 15:13:49, "GuHuangAI" ***@***.***> wrote:

please give me your email, and I'll send my vx to you

**Comment by GuHuangAI** [comment]
@tangwy98 The email is hiddened, please concat with this email: huangai@nudt.edu.cn
